apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: arcpg11
  namespace: arcdc
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: arcpg11
  template:
    metadata:
      labels:
        name: arcpg11
    spec:
      containers:
      - name: arcpg11
        image: mcr.microsoft.com/arc-postgres-11:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
